spring:
  datasource:
        url: jdbc:mysql://localhost:3306/develhope_games
        username: root
        password: admin
  jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: update
